{{- if .Values.ingress.enabled -}}
{{- $fullName := include (printf "phxFunctions.%s.fullname" (index .Values "phx-helm-functions" "version")) (dict "chart" .Chart "values" .Values "release" .Release) -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
{{ include (printf "phxFunctions.%s.annotations" (index .Values "phx-helm-functions" "version")) (dict "values" .Values) | indent 4 }}
{{- with .Values.ingress.annotations }}
  {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
{{ include (printf "phxFunctions.%s.labels" (index .Values "phx-helm-functions" "version")) (dict "chart" .Chart "values" .Values "release" .Release) | indent 4 }}
{{ include "lieferschein.labels" . | indent 4 }}
{{- include (printf "phxFunctions.%s.additional-labels" (index .Values "phx-helm-functions" "version")) (dict "values" .Values)| indent 4 }}
spec:
  rules:
    - host: {{ include (printf "phxFunctions.%s.resolveString" (index .Values "phx-helm-functions" "version")) (dict "value" .Values.ingress.host "values" .Values) | trim }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: 8080
{{- end }}
